### ISSUE TITLE
Help with TE0802

### ISSUE THREAD

**Issue by jsln** [yiskwrt/HelloTrenzTE0802#1]
Hi,

I saw you have a github project using the Trenz TE0802 board. I am trying to run a bare metal application on the Cortex R5, that's all. Do you have any advice about the easiest way to do that? Toolchain/flash/debug tool?

Thanks,
Juan.

**Comment by yiskwrt** [comment]
Hi Juan,

Thanks for your comment.
Actually, there's nothing so special to create/run a baremetal application on the Cortex R5.
As this wiki shows steps to create petalinux project, you need some different actions.
I think (sorry, I have not tested) these ideas will help you now (middle of March, 2021).

Also you'd better read an official document UG1209 (Zynq UltraScale+ MPSoC embeded design tutorial 2019.2)
https://www.xilinx.com/support/documentation/sw_manuals/xilinx2019_2/ug1209-embedded-design-tutorial.pdf

### Reference Project
Trenz provides reference project archive (for 2019.2). 

### Tools
Vivado/Vitis 2019.2 is required.
It's strongly recommended to use 2019.2, instead of the latest (2020.2).
It seems that Vivado 2020.2 have some problem on importing a Trenz's 2019.2 design.

https://twitter.com/yuji_iskwrt/status/1367758703126978561

### Hardware Design
* It's recommended to import Trenz's reference design; you can remove unused parts later.
* run Synthesis -> Implement -> BitStream
* export hardware: FileMenu -> Export -> Hardware (check including bitstream file); you'll find xsa file.
* launch Vitis: FileMenu -> Tools -> Vitis

### Software Design (Chapter 3 in UG1209)
* launch Vitis (maybe with a new workspace)
* create application project
  * specify the xsa file (in Hardware Design) for Platform
  * specify  psu_cortexr5_0, standalone for Domain
  * select an application template
* Now you can start with hello world application

### Running / Debugging
* The microUSB port on TE0802 offers both JTAG access and UART access
* You can start running/debugging your application from a Vitis project.
  * Board would better be set to JTAG boot mode; DipSw S1_1=off, S1_2=off (ON/ON for SD boot mode)
  * Vitis FileMenu -> Debug Configurations -> Xilinx Application Debugger -> Debug
* I don't know much about writing a production baremetal application to an SD card.
  * Vitis should provide some utility to pack items into BOOT.bin. UG1209 might help you.

**Comment by jsln** [comment]
Thanks a lot, that is very helpful.

One last thing, do you know if we have PS MIO pins accessible in this board? I cannot find any reference in the documentation and I would like to drive some GPIOs from a Cortex-R5 application.

**Comment by yiskwrt** [comment]
It seems that we don't have any PS MIO pins that can be used for GPIO.
All the MIO pins are assigned to special functions, otherwise not-used.

https://wiki.trenz-electronic.de/display/PD/TE0802+TRM

In theory, you can start learning control of GPIOs with handling LEDs/Switches on a board.
However, in the reference design, LEDs/Switches are not controlled by the CPU (but by hard-wired control circuit).
You can modify the reference hardware design on Vivado to add an AXI-GPIO IP to directly control LEDs/Switches.

If you need to use GPIO for your own external circuit, the easiest way is to control pins of PMOD connectors.
To achieve that, you should learn,
* How to add/configure AXI-GPIO IP to hardware block design.
* How to define mappings/constraints of pins on PMOD connectors, as other pins in  test_board/constraints/_i_io.xdc
  * You can find mapping from the schematic diagram 
  * then add definitions to _i_io.xdc file.

**Comment by jsln** [comment]
Right, that is what I was suspecting. The TRM mentions GPIO2 (MIO9) and GPIO3 (MIO8) but I didn't find a way of reconfiguring these to enable GPIO function. Instead, they are used for clock generator output.

I need to drive a GPIO from the Cortex-R5 and interrupt on a RX GPIO pin to measure timing precisely. I am planning to learn about the FPGA in the future, but I don't have the time right now. This is such a straightforward use case that I find it a shame that the board design does not include this.

Thanks!

**Comment by yiskwrt** [comment]
Ah, it's very confusing. I'm afraid but you misunderstand TRM about MIO8 and MIO9.
The TRM says U8 (PCIe clock generator chip) has configurable pins which can be {SDA, SCL} or {GPIO2, GPIO3}.
ZynqMP's MIO8 and MIO9 are configured for I2C (SDA, SCL) to communicate with some chips including U8.

Schematics might help you understand.
https://shop.trenz-electronic.de/trenzdownloads/Trenz_Electronic/Development_Boards/TE0802/REV02/Documents/SCH-TE0802-02-2AEU2-A.PDF

Therefore, you cannot use the J14 throughhole as a GPIO for your own design.

If you really want to use MIO for your own purpose, you can reconfigure MIO18, MIO19 to GPIO.
These two pins are assigned to the Grove connector. 
You can reconfigure MIO at property of ZynqMP IP in block design in Vivado.
Please note that:
* Grove connector is 2mm pitch; you might need additional cabling/solder-work.
* Pins are pulled-up
* Of course, you cannot use I2C functions through the Grove connector.

**Comment by jsln** [comment]
Great, it is more clear now, I will use the Grove connector as you suggest.
Thanks a lot!

**Comment by yiskwrt** [comment]
Hi Juan,
How's everything going?
Can I close this ticket?

**Comment by jsln** [comment]
I am learning about the platform and using your helpful comments, that was great help! I am closing the issue now.
